### ISSUE TITLE
Remove $ from filename

### ISSUE THREAD

**Issue by jwils0n** [kentcdodds/watchOnce#2]
The $ in Scope.$watchOnce.js is causing issues with closure-compiler-jar. It thinks the $ is the start of a  variable name. Would you mine renaming it to scope.watchOnce.js or something of the sort?

**Comment by kentcdodds** [comment]
That's kind of weird. But yeah, I don't have a problem renaming it. I'll probably just rename it to `index.js` and `index.min.js`

**Comment by kentcdodds** [comment]
Released as 2.0.0
